alias ll="ls --color=auto -la"
alias mkdir-hadoop="hadoop fs –mkdir -p"
alias ll-hadoop="hadoop fs –ls"
alias put-hadoop="hadoop fs –put"
alias cat-hadoop="hadoop fs –cat"
alias compile-hadoop="hadoop com.sun.tools.javac.Main"
alias gen-jar="jar cf"