version: '3.7'

services:
  traefik:
    image: traefik:v2.6.1
    ports:
      # Exposes port 80 for incomming web requests
      - "80:80"
      # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
      - "8080:8080"
      - "8020:8020"
      - "9866:9866"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/traefik/conf/traefik.yml:/etc/traefik/traefik.yml
    deploy:
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - node.role == manager

  namenode:
    image: ${HADOOP_IMAGE}
    build: ${HADOOP_GIT_URL}
    hostname: namenode
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.namenode.rule=Host(`$NAMENODE_DNS`)"
          - "traefik.http.routers.namenode.entrypoints=web"
          - "traefik.http.routers.namenode.service=namenode"
          - "traefik.http.services.namenode.loadbalancer.server.port=$DFS_NAMENODE_HTTP_PORT"
          - "traefik.tcp.routers.namenode.rule=HostSNI(`*`)"
          - "traefik.tcp.routers.namenode.entrypoints=namenode"
          - "traefik.tcp.services.namenode.loadbalancer.server.port=$DFS_NAMENODE_RPC_PORT"
    environment: 
      - "DFS_NAMENODE_RPC_BIND_HOST=$DFS_NAMENODE_RPC_BIND_HOST"
      - "DFS_REPLICATION=$DFS_REPLICATION"
      - "HADOOP_CONF_DIR=$HADOOP_CONF_DIR"
    volumes: 
      - "./etc/hadoop:$HADOOP_CONF_DIR"
  
  datanode1:
    image: ${HADOOP_IMAGE}
    build: ${HADOOP_GIT_URL}
    hostname: datanode1
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.datanode1.rule=Host(`$DATANODE1_DNS`)"
        - "traefik.http.routers.datanode1.entrypoints=web"
        - "traefik.http.routers.datanode1.service=datanode1"
        - "traefik.http.services.datanode1.loadbalancer.server.port=$DFS_DATANODE_HTTP_PORT"
        - "traefik.tcp.routers.datanode1.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.datanode1.entrypoints=datanode"
        - "traefik.tcp.services.datanode1.loadbalancer.server.port=$DFS_DATANODE_RPC_PORT"
    environment: 
      - "DFS_NAMENODE_RPC_BIND_HOST=$DFS_NAMENODE_RPC_BIND_HOST"
      - "DFS_REPLICATION=$DFS_REPLICATION"
      - "HADOOP_CONF_DIR=$HADOOP_CONF_DIR"
    command: datanode
    volumes: 
      - "./etc/hadoop:$HADOOP_CONF_DIR"

  datanode2:
    image: ${HADOOP_IMAGE}
    build: ${HADOOP_GIT_URL}
    hostname: datanode2
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.datanode2.rule=Host(`$DATANODE2_DNS`)"
        - "traefik.http.routers.datanode2.entrypoints=web"
        - "traefik.http.routers.datanode2.service=datanode2"
        - "traefik.http.services.datanode2.loadbalancer.server.port=$DFS_DATANODE_HTTP_PORT"
        - "traefik.tcp.routers.datanode2.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.datanode2.entrypoints=datanode"
        - "traefik.tcp.services.datanode2.loadbalancer.server.port=$DFS_DATANODE_RPC_PORT"
    environment: 
      - "DFS_NAMENODE_RPC_BIND_HOST=$DFS_NAMENODE_RPC_BIND_HOST"
      - "DFS_REPLICATION=$DFS_REPLICATION"
      - "HADOOP_CONF_DIR=$HADOOP_CONF_DIR"
    command: datanode
    volumes: 
      - "./etc/hadoop:$HADOOP_CONF_DIR"

  datanode3:
    image: ${HADOOP_IMAGE}
    build: ${HADOOP_GIT_URL}
    hostname: datanode3
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.datanode3.rule=Host(`$DATANODE3_DNS`)"
        - "traefik.http.routers.datanode3.entrypoints=web"
        - "traefik.http.routers.datanode3.service=datanode3"
        - "traefik.http.services.datanode3.loadbalancer.server.port=$DFS_DATANODE_HTTP_PORT"
        - "traefik.tcp.routers.datanode3.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.datanode3.entrypoints=datanode"
        - "traefik.tcp.services.datanode3.loadbalancer.server.port=$DFS_DATANODE_RPC_PORT"
    environment: 
      - "DFS_NAMENODE_RPC_BIND_HOST=$DFS_NAMENODE_RPC_BIND_HOST"
      - "DFS_REPLICATION=$DFS_REPLICATION"
      - "HADOOP_CONF_DIR=$HADOOP_CONF_DIR"
    command: datanode
    volumes: 
      - "./etc/hadoop:$HADOOP_CONF_DIR"